# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'browserstack-node-sdk-1.34.33.tgz' # Replace with the name of your secure file
  name: downloadSecureFileStep

- script: |
    ls -al
    printenv
    npm i
    npm uninstall browserstack-node-sdk
    npm i "$(downloadSecureFileStep.secureFilePath)"
    npx browserstack-node-sdk --version
    echo "RUNNING TEST"
    echo $BROWSERSTACK_USERNAME
    npm run sample-test
  env:
    BROWSERSTACK_USERNAME: $(BROWSERSTACK_USERNAME)
    BROWSERSTACK_ACCESS_KEY: ${BROWSERSTACK_ACCESS_KEY}
  displayName: 'Run a multi-line script'